### PR TITLE
Added duplicate controls for non latin keyboard layouts.

### PR DESCRIPTION
**Pull request by AKtor**
It was impossible to control the extention when the keyboard layout is not latin.

### CODE REVIEW

**Comment by igrigorik** [comment]
Hmm, is there a reason why these can't be just configured by the user in options, when they install the extension? Defining duplicates keys in code doesn't scale, since we'll end up with this logic for every major language.

**Comment by AKtor** [comment]
It's can't be configured in options, because char-codes of simbols which ara on the same key are not equal in different layouts. For example, char-code of R is 82 and char-code of cyrillic К is 1050.

You are right that my solution is not scalable. Please deny the pull request.

The correct way to use scan-codes of keys instead of char-codes of simbols. So, needs to use keydown event instead of keypress.

**Comment by igrigorik** [comment]
@AKtor ah, makes sense. Switching to keydown seems like the right solution here. Would you be up for taking a crack at it?

**Comment by AKtor** [comment]
Yes I would)

**Pull request closed without merging**
