### PR TITLE
feat: add volume control (#742)

### PR DESCRIPTION
**Pull request by bk7312**
Add volume control, able to add shortcut to increase or decrease the volume (optional, not in default).

See issue: https://github.com/igrigorik/videospeed/issues/742

### CODE REVIEW

**Comment by mikepiman** [comment]
What number do I enter for "increase volume" and "decrease volume"? 

Before I type something, they both say "value (0.10)", which I do not understand.

Then when I type, the field accepts only: 0, 1, 2, 3,... (i.e., an integer).
Typing 0 causes these key shortcuts to have no effect on volume. 
Typing 1 causes the volume to go essentially to 100% or 0%.

Thanks for any help with this.

**Comment by bk7312** [comment]
You should be entering values between 0 and 1, like 0.05, 0.1 or 0.2. It works like a percentage where 0 means 0% and 1 means 100%. The default 0.1 should be good enough where each increase/decrease will change the volume by 10%.

**Comment by mikepiman** [comment]
Ah, it works great;
the text field does not accept ".05"; it needs the leading 0: "0.05".

**Comment by mikepiman** [comment]
Also,
- [bug]: Often, the volume will go back to its original volume, instantly, about 1-3 minutes after I change it.
- [feature request / issue]: The volume control in the YouTube player doesn't visually change; is it possible for it to change, when we use this extension's volume hotkeys?

**Comment by bk7312** [comment]
Generally, most video streaming websites (like youtube) has their own custom video player to control playback (turn on/off captions, change video quality, prevent you from downloading, etc). This extension works by controlling the video via the [html video tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) and bypasses whatever custom player the website uses. This works most of the time but there's nothing stopping the website's custom player from overwriting whatever changes that were made by this extension.

If you're using youtube specifically, I would recommend using the up/down arrows to adjust the volume. It's not worth the effort hacking the youtube video player (or any other website's custom player) just to change the volume indication.

**Comment by mikepiman** [comment]
True! But the one benefit that I enjoy anout using this extension's volume keys rather than YouTube's, is that they work even when the keyboard focus is not on the video -- for example when typing comments or clicking around the descriptions or suggested videos.

**Pull request merged**
