### PR TITLE
Add honeycode.aws to blacklist (videospeed mangles the site)

### PR DESCRIPTION
**Pull request by russelldavis**
See #754

I'm not sure what's causing the issue, but this adds the site to the blacklist until it gets fixed.

### CODE REVIEW

**Comment by Xerothusian** [comment]
Would it be unwise to simply allow people to do it themselves?

**Comment by igrigorik** [comment]
Seems to be working a-ok now! :)

**Comment by russelldavis** [comment]
It's still broken.

**Comment by igrigorik** [comment]
Odd, which page / video are you testing?

**Comment by russelldavis** [comment]
Just the home page. The videos are all larger than they should be (for reasons explained in #754), so the page has horizontal scrollbars when it shouldn't (at least on a 15" Macbook Pro screen). The issue is even more obvious if you click the image at the top of the page which shows a larger video player in a lightbox (and two layers of horizontal scrollbars).

**Pull request closed without merging**
