### PR TITLE
Fix positioning for videos with non-zero offsetTop/offsetLeft

### LINKED ISSUE #786: controller position botched on youtube
in https://github.com/igrigorik/videospeed/pull/752 i changed how the controller is positioned. 
this change is landed in git, but hasn't gone to CWS yet.

today @pepijnmm  reported a bug about my change:

> @paulirish For me this merge breaks the youtube controller position(just noticed hadn't updated in a while)
> I tested compared to enforce normal white-space rendering for controller (#753) so only this commit changed things
> Before merge:
> Screenshot_8
> after merge
> Screenshot_7

i can repro this as well.

fixing this is going to require some more thinking (and some testing..)  

We'll have to find a positioning calculation that's respectful of offsetParent but still gives results across all target sites.

### PR DESCRIPTION
**Pull request by russelldavis**
Fixes #786

### CODE REVIEW

**Comment by russelldavis** [comment]
Yep I've tested a bunch on Youtube. I don't have a Hulu subscription either, but I've tested on other sites that were affected by the same bug as Hulu (due to a `transform` on the video location), e.g. Reddit. I've also tested on other sites that were affected by #786, e.g. https://mlb.com/news.

Also tested on several other sites in general, e.g. Amazon Prime Video and Vimeo.

**Comment by pepijnmm** [comment]
works good for me too!
for hulu I tried https://www.hulu.com/movie/good-boy trailer (didn't want horror but could not find other trailers XD )

I will close #845 

thanks! Hope they merge it soon.

**Comment by pepijnmm** [comment]
@igrigorik do you have time to check this one out to fix to position of the vsc?

**Review by igrigorik — APPROVED** [review]
Apologies for the delay on the review and thank you for the fix! 👍🏻

**Comment by paulirish** [comment]
@russelldavis thanks for fixing this. 🙏 

back when i introduced the bug in #752 i said

> `getBoundingClientRect` takes transforms into account, but otherwise I think it has consistent semantics with `offsetLeft`/`offsetTop`. …

well... really dumb of me not to remember or consider a positioned parent's effect.  

Appreciate you cleaning up my mess. :)

**Pull request merged**
