### PR TITLE
Let each controller track its own speed (fix #457)

### LINKED ISSUE #457: Speed resets when video quality changes
When the "Remember playback speed" option is unchecked, and when the quality of the video on youtube changes (due to changing network conditions, etc), the video playback speed resets to 1x each time. Does not happen when remember playback speed option is checked, but with the latest update, there is [this issue](https://github.com/igrigorik/videospeed/issues/455#issuecomment-485296516). 

Not sure, if this is the expected behaviour, but I would expect the video speed to remain the same (not reset to 1x) even when the remember playback speed option is unchecked.

### PR DESCRIPTION
**Pull request by jacobcolbert**
Fixes #457 

Prevent source changes from changing speed in same video container.

### CODE REVIEW

**Comment by jacobcolbert** [comment]
Unfortunately after getting rid of a variable called speed I have had to reintroduce a variable called speed! But I think it is necessary. Tracking current speeds by source has solved some problems, but created #457 because the source changes despite being the same video. Each controller now can track its own speed and if the source of the video tag is changed it will pick up with the same speed.

**Comment by igrigorik** [comment]
Wait, doesn't this bring us back to where we started? As in, what's the point or value in having the track by source logic if we're back to controller+video pair be the master?

**Comment by jacobcolbert** [comment]
The master is still the speeds[src], but if that is not defined then it takes the speed from the controller. 

The global dict solves the problem of the same source being continuously passed between newly created video tags. (The youtube fullscreen issue #370)

Giving each controller a speed field solves the problem that this creates when a video tag has its source switched (#457)

**Comment by igrigorik** [comment]
Ok, yeah, that makes sense.

**Pull request merged**
