### PR TITLE
Add ability to disable website keybindings for show/hide controller (Fixes: #526)

### PR DESCRIPTION
**Pull request by thewheat**
- Adding the select dropdown to allow disabling website keybinds for the "Show/hide controller" option similar to the other keybindings
- it only shows when clicking "show experimental features"
image

**Demo**
Demo of it showing only after clicking "show experimental features" and of it being able to persist on saving
show-hide

### CODE REVIEW

**Comment by jacobcolbert** [comment]
This looks nice, thanks for the work. But I am left wondering why show/hide is treated differently from every other feature. I would prefer a small refactor from the original to just treat show/hide like everything else. It seems like this was explicitly not done in #350. Do you have any ideas why? @igrigorik @canarslan12

**Comment by igrigorik** [comment]
@jacobcolbert scratching my head as well, I think this was an oversight as I don't recall any specific reason why we decided to specifically omit this feature. Also, +1 to your recommendation on refactor.

**Comment by thewheat** [comment]
Cool. By refactor just meaning to make it styled like the rest with  
- `Show/hide controller` as a form select input
- And for the non customizable input to be disabled?

image

**Comment by jacobcolbert** [comment]
In terms of external behavior, yes that is exactly what I mean.

In the code I mean that show/hide is treated by itself as an exceptional case while every other feature is treated uniformly. Specifically, in options.html it is implemented as <div class="row"> rather than <div class="row customs"> like all of the following features. And in the options.js it is not included as an option in the dropdown. 

The code should treat all of these features the same, so that if we change things in the future it will automatically affect all of them equivalently.

**Comment by igrigorik** [comment]
Nice! I think this looks good now, nice touch on custom bindings carryover.. 

@jacobcolbert any feedback before we merge?

**Comment by jacobcolbert** [comment]
Looks great to me. Gonna fix some indentation errors that were already there. 

Very nice touch on carrying over the custom bindings. Would prolly have missed that myself. Can that code be removed in the next version after this is pushed live?

**Comment by thewheat** [comment]
Hmmm that's a good question. 

I think the part in `inject.js` should be kept

https://github.com/igrigorik/videospeed/blob/29788ba82ad93c2798f26676acedf23ca662105b/inject.js#L93-L101

It is similar to the current code to initialize the other shortcuts
https://github.com/igrigorik/videospeed/blob/29788ba82ad93c2798f26676acedf23ca662105b/inject.js#L26-L71

* * * 
The `options.js` change is dependent if a `storage.keyBindings` has been saved after the update as that is when the new `display` action is set via `save_options`. 

Then we can remove this line

https://github.com/igrigorik/videospeed/blob/29788ba82ad93c2798f26676acedf23ca662105b/options.js#L187-L190

And also this following one as `item["key"]` would be defined

https://github.com/igrigorik/videospeed/blob/29788ba82ad93c2798f26676acedf23ca662105b/options.js#L197-L199

**Pull request merged**
