### PR TITLE
Easy perf  fix on speed change

### PR DESCRIPTION
**Pull request by asselin**
If we have the video element, then there's no need to call getController(), since the controller is attached to the video element directly

### CODE REVIEW

**Comment by asselin** [comment]
Fixed the other cases where the whole document was getting crawled.  I guess it's not "easy" perf fixes anymore, but, hey

**Comment by ChadBailey** [comment]
Thanks so much for this! I know some people have been complaining about the performance, so glad to see any fixes for that. I'm going to test this with the other pending PR's as soon as I can. I planned to today but I had some unplanned maintenance that set me back

**Comment by ChadBailey** [comment]
I tried navigating this merge conflict myself, but wasn't confident I wouldn't undo some of the changes in #654 

Could I have you try resolving the conflicts now that I've gotten the other bugfixes merged in?

**Comment by asselin** [comment]
No worries, I'll take a look. Are you available now to spend some time on this project?

**Comment by ChadBailey** [comment]
yea, i should have the capacity to spend some more time now. not back to 100%, but enough that i feel i should have at least a couple of hours per week to spare

**Comment by igrigorik** [comment]
@asselin @ChadBailey either of you still have bandwidth to rebase this? On quick scan, this looks like a good improvement, curious to take it out for a test drive.

**Comment by asselin** [comment]
I had forgotten about this.  Actually, I should have some time to work on this in the near future.  This wound up turning into a lot of changes, so maybe I'll try to make it more incremental.

**Comment by igrigorik** [comment]
👍

**Comment by asselin** [comment]
This is superseded by #708

**Pull request closed without merging**
