### PR TITLE
Fix for Chrome 71 touch events bug

### LINKED ISSUE #213: video control panel disappears on Win + touchpad
This was reported and fixed once already but it's happening again:
I open a youtube video which has 1.00 speed by default.
I keep pressing the increase speed button.
By the time I reach ~1.75, the control panel hides while I'm still clicking, which means I pause the video by accident.

Actually that was the original issue, but nowadays it happens even more frequent.

### LINKED ISSUE #389: Mouse events aren't working
I can use D and S to slow and speed up videos but the overlap isn't responding to clicks.
Using "Chrome 71.0.3578.53 beta (64-bit)"
I've restarted chrome, disabled & renabled the extension.

When I hover over the overlay I get different mouse pointers but I can't drag it and clicking does nothing.

### PR DESCRIPTION
**Pull request by canarslan12**
Fixes #389, #396, #395, #394, #398 (duplicates)
Also fixes #213 video control panel disappears sometimes after click which was caused by double clicking was canceling. this issue was most commented issue.

### CODE REVIEW

**Comment by Leglaw** [comment]
Works 👍

**Comment by azuzunaga** [comment]
On my end, when clicking on any part of the shadow div, the video jumps to full-screen.

**Comment by canarslan12** [comment]
Can you try with https://github.com/canarslan12/videospeed

**Comment by poush** [comment]
Working fine on Chrome - macOS

**Comment by igrigorik** [comment]
@canarslan12 thank you!

**Comment by kikidesignnet** [comment]
how do i fix this??

**Comment by igrigorik** [comment]
Your Chrome should auto-update the extension within the next 24 hours — no action required.

**Comment by azuzunaga** [comment]
@canarslan12 sorry for the delay in replying. Video still goes full-screen on Vimeo / Vimeo hosted players when clicking anywhere on the shadow div. I was able to replicate the issue with version 0.5.3, and https://github.com/canarslan12/videospeed, `master` branch (as of today).

Thanks for your work on this btw!! And let me know if there is anything I can do to help!

**Pull request merged**
