### PR TITLE
vk site fix attemp #236

### PR DESCRIPTION
**Pull request by canarslan12**
not sure about all across vk side, it might break something else

### CODE REVIEW

**Comment by SeanSilke** [comment]
It is quite good.

**Comment by igrigorik** [comment]
What problem is this solving? 

FWIW, I would strongly prefer not to start littering code with origin ifdefs. Is there a more generic solution to a problem you're trying to solve?

**Comment by SeanSilke** [comment]
@igrigorik This is solving https://github.com/igrigorik/videospeed/issues/236.

**Comment by igrigorik** [comment]
Ah, I see.. interesting. Couple of notes..

- Agree that this shouldn't be vk.com specific
- Current logic prevents controller from initializing if networkState is 0 when it's appended to the DOM (which makes sense), but it also does not account for case where networkState changes later. Is there a callback that we can or should listen to to invoke the registration?
  - As this, this would prevent VC from starting on any 'lazy-loaded' videos.
- There's some conceptual overlap here with https://github.com/igrigorik/videospeed/commit/bbb8a7354b6e9ff6e9cf825f5d9dd89c5a87e60c - we should think about if/how we can refactor that with this work.

**Comment by canarslan12** [comment]
I think vk.com using 'lazy-loaded' videos and no problem happening.
do you suggest me to add `target.addEventListener('_networkStatechange(?)_', function(event) {`?

**Comment by igrigorik** [comment]
Yes, except.. I don't believe there is such a callback, which is part of the problem?

**Comment by canarslan12** [comment]
we can use some of them but I'm not sure about it, i think onprogress will be better. 
> loadstart
> durationchange
> loadedmetadata
> loadeddata
> progress
> canplay
> canplaythrough
also we can do this for all sites which use lazyloading differently. It will be good enhancement for extension.

**Comment by igrigorik** [comment]
@canarslan12 can we remove the vk.com clause in this PR? What will it break? As stated earlier, I'd like to avoid site-specific rules whenever possible.

**Comment by igrigorik** [comment]
Closing. If this is still an issue for vk, let's open a new bug and discuss the possible approaches there.

**Pull request closed without merging**
