### PR TITLE
Add support for rewind and fast forward in netflix.com

### PR DESCRIPTION
**Pull request by stephenbrady**
Resolve issues #84 and #260

### CODE REVIEW

**Comment by igrigorik** [comment]
Wow, neat-o. Is this a documented / stable API?

**Comment by stephenbrady** [comment]
I'm not aware of it being documented. I'd be surprised if they explicitly support client-side interaction. It seems stable though. I got a clue about the API from this Stackoverflow response from October 2017 (https://stackoverflow.com/questions/42105028/netflix-video-player-in-chrome-how-to-seek). It hasn't changed in four years, so there's that. Data point of one: I've been using it all year on my fork and haven't had any problems.

One caveat is that I added this second commit to the PR to be more defensive about what messages are handled in the presence of other code in the sandbox sending/receiving messages. It might be needlessly defensive, though, and it presumes that Netflix is being served from netflix.com, which I don't know to be true for all geographies. The host checking could cause more problems for users than it's worth - maybe.

**Comment by pepijnmm** [comment]
o nice!

**Comment by igrigorik** [comment]
> It hasn't changed in four years, so there's that. Data point of one: I've been using it all year on my fork and haven't had any problems.

That's more than I hoped for, tbh. On the defensive side: yeah, I think if we want to land this then we might as well accept the risk and make it work across all geographies. This means doing a more relaxed check in hostname and removing the defensive commit. You OK with that?

**Comment by stephenbrady** [comment]
> This means doing a more relaxed check in hostname and removing the defensive commit. You OK with that?

On this point, in isolation, I'm agnostic. Happy to back it. out.

However, I also have this line in there (https://github.com/igrigorik/videospeed/pull/781/files#diff-8dcb72b9c92c5fa9eb8602ce15b90717f8717699b5865db86078df006be5c4c0R801), which limits injecting the message handling script only when it's being loaded on netflix.com. It's not a huge deal if this is being instantiated on every page that videospeed is being loaded into, but Web page bloat is death by a thousand cuts.

So if we remove the hostname checking for the postMessage, then it would only make sense to remove the conditional injection of the script too because if Netflix is ever served from a host other than netflix.com, the end-to-end will still break.

Or we go the other way, and just leave the PR as is and just react if people report Netflix as not being fixed due to different serving domains. My cursory look suggests netflix.com is the only serving host worldwide right now. Besides, rewind and forward with videospeed doesn't work on netflix.com right now anyway, so we're at least giving those videospeed users a fix and everyone else is status quo.

**Comment by igrigorik** [comment]
> So if we remove the hostname checking for the postMessage, then it would only make sense to remove the conditional injection of the script too because if Netflix is ever served from a host other than netflix.com, the end-to-end will still break.

That's not what I was thinking. Rather, relaxing the constraint on matching the suffix. Effectively, if we see a valid `www.netflix....`. Not without risk of false positives but I agree with you that we don't want to blindly insert this on every page.

**Comment by russelldavis** [comment]
It probably makes sense to match on any (or no) subdomain of Netflix as well. So, as a regex, `^(.*\.)?netflix\.[^.]*$`

**Comment by igrigorik** [comment]
^ +1.

**Comment by pepijnmm** [comment]
As far as I know Netflix.com is the universal address in all countries. Urls like Netflix.ru / Netflix.nl get redirected to www.netflix.com .

**Comment by stephenbrady** [comment]
Sadly, this PR may be moot now. Of all things, it looks like the API has changed after four years! Must have happened in the last month or so? I poked around the object graph, but I'm not seeing how to access the player controller object. Unless someone figures that out, it looks like we should close the PR.

**Comment by igrigorik** [comment]
Doh. Thanks for chasing this.. one day!

**Pull request closed without merging**
