### PR TITLE
Differentiate uppercase and lowercase keyboard shortcuts, make controller size configurable, fix some issues on reddit, and netflix, maybe some more stuff

### LINKED ISSUE #499: Feature Request: Larger buttons on screen
Installed this for seniors, they cannot easily see or click the buttons.

Could there be options for making them bigger? and options for other corners of screen?

Thanks alot.

### PR DESCRIPTION
**Pull request by magnus-ISU**
Fixes #499 #881, my request #906, some issues related to #860 though not for facebook itself I think, as well as [some](https://github.com/codebicycle/videospeed/issues/158) issues [from](https://github.com/codebicycle/videospeed/issues/166) the firefox version.

Sorry for absolutely garbage PR, I did all my proper work on the Firefox version and couldn't figure out how to merge it properly

This refactors a lot of input code. The way it does so is by mostly ignoring the keyCode attribute of an input event now and instead using the string key which contains more information and in a more human-readable way. Unfortunately, this currently means it breaks any preconfigured options a user has set and users will need to reconfigure it. Assuming this is unacceptable (I assume it is) I can add in a migration strategy; but I need to know how best that done.

I decided the default keybindings are all for lowercase letters; but before they would be either. Is that an acceptable change?

I also removed the old 5.3.0 settings conversion code because its been here long enough I think. In doing so, I was able to simplify some logic. Additionally, vine.co does not really exist anymore so disabling the extension there by default is unneeded I think. Let me know if you want me to revert the vine.co change, that was mostly spur-of-the-moment.

I need testing for numpad keys to see if they still work the same. I wrote this all on a laptop without them. I can do this myself though before I get back to you on some of my other questions, its important to mention though I think.

Improves the quality of the code in several places, adding more useful comments and improving code reuse. Creates a file `constants.js` which contains common values between `inject.js` and `options.js` - unfortunately, because user scripts aren't modules, the code has to be duplicated at the top of `inject.js`.

Changes the UI slightly to be able to do #499. I tried to get it as close to the original as possible, but I didn't 100% succeed. Let me know if you think it needs to be changed any more.

There are several TODOs marked around the code where I wasn't sure what was going on and need review to tell me if my comments are correct or not. They mostly relate to other ways I feel refactoring could be done to reduce redundant or seemingly-unused information.

### CODE REVIEW

**Comment by magnus-ISU** [comment]
I've added several more improvements to my fork (not in this MR); mouse scrolling support, reloading hotkeys without reloading webpages, some other fixes.

I don't have any interest in chromium, and I'm maintaining my own firefox fork now too, so I don't really care much if this gets merged. However, I'll leave it here in case someone else wants these features.

Thanks for creating the extension!

**Comment by ChadBailey** [comment]
I appreciate your contributions none the less. I am currently working on a refactoring effort in #963 which I hope to be able to expand the compatibility of the extension to include other browsers.

I will leave this here for now without merging, as I'm unable to dedicate the needed time to look through it. In an ideal world, we get everything working cleanly in parent project and you can spend your time helping contribute to it rather than having to maintain your fork.

**Comment by FedeCuci** [comment]
I have tested this fork on Firefox (#973) and it works well! Not sure what else I can do to test it further @ChadBailey but I'd be happy to help where I can. Let me know 👍

**Comment by ChadBailey** [comment]
Thank you for testing! I think I'll try and push to get this merged in a couple of days. Was hoping to hear from @igrigorik with his opinions before opening a PR.

I'll have to do the final cleanup steps I have in the bugs sections before I do of course

**Comment by igrigorik** [comment]
> I decided the default keybindings are all for lowercase letters; but before they would be either. Is that an acceptable change?

Hmm. In practice, I've found that having both caps and lowercase mapped to the same function is a useful feature. For example, on vimeo cap-{CMD} does not trigger their UI logic and acts as a nice workaround. I think my preference would be to keep that behavior as is.

**Comment by FedeCuci** [comment]
> > I decided the default keybindings are all for lowercase letters; but before they would be either. Is that an acceptable change?
> 
> Hmm. In practice, I've found that having both caps and lowercase mapped to the same function is a useful feature. For example, on vimeo cap-{CMD} does not trigger their UI logic and acts as a nice workaround. I think my preference would be to keep that behavior as is.

I agree. I would keep both caps and lowercase mapped to the same function as well as there might be cases in which the user forgets the caps-key on, and might be confused as to why the controls are not working. It would offer more customization but would be harder to configure and probably just complicate things.

A solution to satisfy both approaches is to allow the user to chose what they want through a checkbox for example. However the default should be having both caps and lowercase mapped to the same function imo.

**Comment by igrigorik** [comment]
Closing, https://github.com/igrigorik/videospeed/issues/963 refactor lands bits and pieces of the work here — ty!

**Pull request closed without merging**
