### PR TITLE
Added auto test and build CICD pipeline to pull requests

### PR DESCRIPTION
**Pull request by ChadBailey**
Restructured code to separate configs and artifacts from code
Created node project and added testing packages
Added github action for running tests on pull requests
Added demo tests to demonstrate how to use them
Updated CONTRIBUTING.md as needed
Created local pre-commit hook to automatically test and style on push (see screenshot)
image

In the event of a failing scenario (feature), the end user is given a detailed explanation of what went wrong and why like this

image

In the event of a failing unit test, the commit is blocked and the user is given a detailed explanation of the failed test

image

In the event of incorrect styling, the user is notified of the failed style check. At their option, the user can issue the command `npm run fixup` to have their code auto-formatted

image

### CODE REVIEW

**Comment by ChadBailey** [comment]
Sorry, I may have gotten a bit carried away with this one. I went in to simply restructure into subdirectories for packaging. I guess I figured while I was messing with the github actions I should go ahead and add one for formatting like we discussed in #578, so I did that which lead me to thinking we should add some automated testing too since we're checking style... And here we are

**Comment by ChadBailey** [comment]
> A bit confused.. :-)

Your confusion is understandable, I didn't really go into much detail here. This is perhaps just a by-product of me playing into my strengths. I am a test architect, so this is the thing I do as a day job. I suppose I just wanted to gift the project with it.

> What do we mean by allow GH actions? We already have the action to publish to Chrome store running a-ok.

What I meant was to restructure the folders so that only the addon itself is in the zip file. This is just a best practice, as we wouldn't ever want to accidentally package configs or other sensitive things in the release. I realize this is no corporation, but that's the rationale behind it.

> Can we actually meaningfully test the behaviors we're after? If we want to tackle that, I'd suggest separating that into separate PR.

I also wanted to begin writing some meaningful tests, which I saw the folder structure to be a prerequisite to so that the tests aren't packaged with the addon.

Finally, it really bugged me that the styling wasn't automated the way I wanted it to be, so I added the quality checks for every pull request (you can see that it worked as it says "All checks have passed" and see the detailed testing log output).

That's why all of the big changes, and why I didn't include any meaningful tests yet, I was just trying to prepare the repo for those soon to come changes.

I hope all of that makes sense. Let me know if you have any other concerns.

**Comment by ChadBailey** [comment]
I have updated my original post to clearly communicate what's been changed and why

**Comment by igrigorik** [comment]
Thanks for the detailed explanation. Overall, this looks great. My only hesitation is/was the stand-in tests.. Still wondering if we'll actually be able to meaningful test the behaviors that we're after? If you're confident that the answer is "yes" then.. great, let's land this!

**Comment by ChadBailey** [comment]
> Still wondering if we'll actually be able to meaningful test the behaviors that we're after?

I see what you mean. I'm still new to JS land, so I can't say with confidence there wont be another road block yet to come on this.

I am going to take a swing at making a couple of meaningful tests to include with this in place of the examples so that I can give a real demo of how it would be used. That will ensure that the answer to your question is yes, as well as make the changes more valuable.

**Comment by igrigorik** [comment]
Perfect, yep, thank you!

**Comment by ChadBailey** [comment]
I don't anticipate working on this soon since there are more pressing customer-facing issues to work on. Closing - I will reopen once I get the chance to revisit.

**Pull request closed without merging**
