### PR TITLE
Add Safari extension Support

### PR DESCRIPTION
**Pull request by Kyle-Ye**

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
截屏2021-01-31 下午5 18 37
截屏2021-01-31 下午5 19 10

**Comment by parkleo121212** [comment]
I want to use this extension on iOS 15 and, iPadOS 15 too.
Can you make Safari extension for mobile device please?

**Comment by Kyle-Ye** [comment]
> I want to use this extension on iOS 15 and, iPadOS 15 too.
> Can you make Safari extension for mobile device please?

I've tested it successfully on my iPad & iPhone. And will update the source soon on https://github.com/Kyle-Ye/videospeed.

I have the paid Apple Developer Account and can upload the app to App Store, but will it against the MIT license? 

What should I do if we want the app on App Store?  @igrigorik

**Comment by parkleo121212** [comment]
> > I want to use this extension on iOS 15 and, iPadOS 15 too.
> > Can you make Safari extension for mobile device please?
> 
> I've tested it successfully on my iPad & iPhone. And will update the source soon on https://github.com/Kyle-Ye/videospeed.
> 
> I have the paid Apple Developer Account and can upload the app to App Store, but will it against the MIT license?
> 
> What should I do if we want the app on App Store? @igrigorik @ChadBailey

Wow! If there are no problem with licenses etc, I'd like to get a test flight link. Thanks you so much!

**Comment by Kyle-Ye** [comment]
> > > I want to use this extension on iOS 15 and, iPadOS 15 too.
> > > Can you make Safari extension for mobile device please?
> > 
> > 
> > I've tested it successfully on my iPad & iPhone. And will update the source soon on https://github.com/Kyle-Ye/videospeed.
> > I have the paid Apple Developer Account and can upload the app to App Store, but will it against the MIT license?
> > What should I do if we want the app on App Store? @igrigorik @ChadBailey
> 
> Wow! If there are no problem with licenses etc, I'd like to get a test flight link. Thanks you so much!

Will post a TF link here once apple proves it.

**Comment by Kyle-Ye** [comment]
> > > I want to use this extension on iOS 15 and, iPadOS 15 too.
> > > Can you make Safari extension for mobile device please?
> > 
> > 
> > I've tested it successfully on my iPad & iPhone. And will update the source soon on https://github.com/Kyle-Ye/videospeed.
> > I have the paid Apple Developer Account and can upload the app to App Store, but will it against the MIT license?
> > What should I do if we want the app on App Store? @igrigorik @ChadBailey
> 
> Wow! If there are no problem with licenses etc, I'd like to get a test flight link. Thanks you so much!

TF link: https://testflight.apple.com/join/fyXYXyHP (Feedback is welcome)

**Comment by calibers16** [comment]
I have waited for this Safari extension for so long! Can I join the TF, or at least find out when we can expect this in the App Store? I would gladly pay money for this!!

**Comment by Kyle-Ye** [comment]
> I have waited for this Safari extension for so long! Can I join the TF, or at least find out when we can expect this in the App Store? I would gladly pay money for this!!

It’s already on the App Store for free. Check out here @calibers16 https://github.com/Kyle-Ye/Video-Speed-Controller

**Pull request closed without merging**
